db_seed:
	python -m app.db.seeding.seed_db # Make sure this matches the folder path to the seeding script

db_seed_base:
	python -m app.db.seeding.seed_db_base # Make sure this matches the folder path to the seeding script
