"""Yet another descriptive migration

Revision ID: 23f29fb8eaee
Revises:
Create Date: 2025-11-30 18:43:07.240842

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23f29fb8eaee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binary_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MOOD",
                "SYMPTOMS",
                "APPETITE",
                "DIGESTION",
                "SWELLING",
                "PHYSICAL_ACTIVITY",
                "OTHERS",
                name="binarymetriccategory",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "doctor_account_creation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("middle_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "qualification_option",
            sa.Enum("MD", "DO", "MBBS", "MBChB", "BMed", "BM", name="doctorqualificationoption"),
            nullable=False,
        ),
        sa.Column("qualification_img_key", sa.String(), nullable=False),
        sa.Column(
            "account_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="accountcreationrequeststatus"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("reject_reason", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "doctor_qualifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qualification_img_key", sa.String(), nullable=True),
        sa.Column(
            "qualification_option",
            sa.Enum("MD", "DO", "MBBS", "MBChB", "BMed", "BM", name="doctorqualificationoption"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("protein_per_100g", sa.Float(), nullable=True),
        sa.Column("carbs_per_100g", sa.Float(), nullable=True),
        sa.Column("fats_per_100g", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nutritionist_account_creation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("middle_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "qualification_option",
            sa.Enum(
                "BSC_NUTRITION",
                "BSC_DIETETICS",
                "MSC_NUTRITION",
                "MSC_DIETETICS",
                "RD",
                "RDN",
                "CNS",
                "DIPLOMA_CLINICAL_NUTRITION",
                "DIPLOMA_NUTRITION",
                "CERTIFIED_NUTRITIONIST",
                name="nutritionistqualificationoption",
            ),
            nullable=False,
        ),
        sa.Column("qualification_img_key", sa.String(), nullable=False),
        sa.Column(
            "account_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="accountcreationrequeststatus"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("reject_reason", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "nutritionist_qualifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qualification_img_key", sa.String(), nullable=True),
        sa.Column(
            "qualification_option",
            sa.Enum(
                "BSC_NUTRITION",
                "BSC_DIETETICS",
                "MSC_NUTRITION",
                "MSC_DIETETICS",
                "RD",
                "RDN",
                "CNS",
                "DIPLOMA_CLINICAL_NUTRITION",
                "DIPLOMA_NUTRITION",
                "CERTIFIED_NUTRITIONIST",
                name="nutritionistqualificationoption",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scalar_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("unit_of_measurement", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
        sa.UniqueConstraint("unit_of_measurement"),
    )
    op.create_table(
        "users",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("profile_img_key", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("middle_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "VOLUNTEER_DOCTOR", "PREGNANT_WOMAN", "NUTRITIONIST", name="userrole"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "community_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expo_push_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("is_seen", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "THREAD_LIKE",
                "THREAD_COMMENT",
                "COMMENT_LIKE",
                "COMMENT_REPLY",
                "NEW_ARTICLE",
                "APPOINTMENT_REMINDER",
                "APPOINTMENT_REQUEST",
                "PRIVATE_MESSAGE",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("data", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_is_seen"), "notifications", ["is_seen"], unique=False)
    op.create_index(op.f("ix_notifications_recipient_id"), "notifications", ["recipient_id"], unique=False)
    op.create_table(
        "nutritionists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qualification_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["nutritionist_qualifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pregnant_women",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_app_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "volunteer_doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qualification_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["doctor_qualifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volunteer_doctor_id", sa.Integer(), nullable=False),
        sa.Column("mother_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING_ACCEPT_REJECT", "ACCEPTED", "REJECTED", "COMPLETED", name="appointmentstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["pregnant_women.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_doctor_id"],
            ["volunteer_doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "community_thread_likes",
        sa.Column("liker_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["liker_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["community_threads.id"],
        ),
        sa.PrimaryKeyConstraint("liker_id", "thread_id"),
    )
    op.create_table(
        "edu_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "NUTRITION",
                "BODY",
                "BABY",
                "FEEL_GOOD",
                "MEDICAL",
                "EXERCISE",
                "LABOUR",
                "LIFESTYLE",
                "RELATIONSHIPS",
                name="eduarticlecategory",
            ),
            nullable=False,
        ),
        sa.Column("img_key", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["volunteer_doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("logged_on", sa.Date(), nullable=False),
        sa.Column("systolic", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("diastolic", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["pregnant_women.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journal_entries_logged_on"), "journal_entries", ["logged_on"], unique=False)
    op.create_table(
        "kick_tracker_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mother_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["pregnant_women.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nutritionist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("img_key", sa.String(), nullable=True),
        sa.Column("prepare_time_minutes", sa.Integer(), nullable=False),
        sa.Column("serving_count", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutritionist_id"],
            ["nutritionists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saved_volunteer_doctors",
        sa.Column("mother_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_doctor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["pregnant_women.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_doctor_id"],
            ["volunteer_doctors.id"],
        ),
        sa.PrimaryKeyConstraint("mother_id", "volunteer_doctor_id"),
    )
    op.create_table(
        "thread_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("commenter_id", sa.Integer(), nullable=False),
        sa.Column("commented_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commenter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["community_threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_binary_metric_logs",
        sa.Column("journal_entry_id", sa.Integer(), nullable=False),
        sa.Column("binary_metric_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["binary_metric_id"],
            ["binary_metrics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("journal_entry_id", "binary_metric_id"),
    )
    op.create_table(
        "journal_scalar_metric_logs",
        sa.Column("journal_entry_id", sa.Integer(), nullable=False),
        sa.Column("scalar_metric_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scalar_metric_id"],
            ["scalar_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("journal_entry_id", "scalar_metric_id"),
    )
    op.create_table(
        "kick_tracker_kicks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kick_at", sa.DateTime(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kick_tracker_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("unit_of_measurement", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "ingredient_id"),
    )
    op.create_table(
        "saved_edu_articles",
        sa.Column("saver_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["edu_articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saver_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("saver_id", "article_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saved_edu_articles")
    op.drop_table("recipe_ingredients")
    op.drop_table("kick_tracker_kicks")
    op.drop_table("journal_scalar_metric_logs")
    op.drop_table("journal_binary_metric_logs")
    op.drop_table("thread_comments")
    op.drop_table("saved_volunteer_doctors")
    op.drop_table("recipes")
    op.drop_table("kick_tracker_sessions")
    op.drop_index(op.f("ix_journal_entries_logged_on"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_table("edu_articles")
    op.drop_table("community_thread_likes")
    op.drop_table("appointments")
    op.drop_table("volunteer_doctors")
    op.drop_table("user_app_feedback")
    op.drop_table("pregnant_women")
    op.drop_table("nutritionists")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_seen"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("expo_push_tokens")
    op.drop_table("community_threads")
    op.drop_table("admins")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("scalar_metrics")
    op.drop_table("nutritionist_qualifications")
    op.drop_table("nutritionist_account_creation_requests")
    op.drop_table("ingredients")
    op.drop_table("doctor_qualifications")
    op.drop_table("doctor_account_creation_requests")
    op.drop_table("binary_metrics")
    # ### end Alembic commands ###
