"""Added 'commented_at' datetime field for 'thread_comments'

Revision ID: 359831da2ee7
Revises: 892cf78f9808
Create Date: 2025-10-25 00:56:26.802170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359831da2ee7'
down_revision: Union[str, Sequence[str], None] = '892cf78f9808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_comments', sa.Column('commented_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_comments', 'commented_at')
    # ### end Alembic commands ###
