"""Added initial tables

Revision ID: 36dc78c86f3a
Revises: 
Create Date: 2025-10-16 16:43:31.490076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dc78c86f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('medical_credential_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cred_img_url', sa.String(length=255), nullable=False),
    sa.Column('credential', sa.String(length=50), nullable=False),
    sa.Column('full_meaning', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential'),
    sa.UniqueConstraint('full_meaning')
    )
    op.create_table('metric_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('edu_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['edu_article_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['metric_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('community_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnant_women',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_img_url', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('volunteer_specialists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('med_cred_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['med_cred_id'], ['medical_credential_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bump_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('bump_img_url', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['pregnant_women.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'MISSED', name='consultstatus'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['pregnant_women.user_id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['volunteer_specialists.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['pregnant_women.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_option_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_option_id'], ['metric_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pregnant_women.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'metric_option_id', 'logged_at')
    )
    op.create_table('saved_edu_articles',
    sa.Column('saver_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['edu_articles.id'], ),
    sa.ForeignKeyConstraint(['saver_id'], ['pregnant_women.user_id'], ),
    sa.PrimaryKeyConstraint('saver_id', 'article_id')
    )
    op.create_table('saved_volunteer_specialists',
    sa.Column('saver_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saver_id'], ['pregnant_women.user_id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['volunteer_specialists.user_id'], ),
    sa.PrimaryKeyConstraint('saver_id', 'specialist_id')
    )
    op.create_table('thread_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['community_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_comments')
    op.drop_table('saved_volunteer_specialists')
    op.drop_table('saved_edu_articles')
    op.drop_table('metric_logs')
    op.drop_table('journal_entries')
    op.drop_table('consultations')
    op.drop_table('bump_entries')
    op.drop_table('volunteer_specialists')
    op.drop_table('pregnant_women')
    op.drop_table('community_thread')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('metric_options')
    op.drop_table('edu_articles')
    op.drop_table('roles')
    op.drop_table('metric_categories')
    op.drop_table('medical_credential_options')
    op.drop_table('edu_article_categories')
    # ### end Alembic commands ###
