"""Modification to have 2 types of metrics

Revision ID: 5b51b0ac06f6
Revises: 8042c4d8a60f
Create Date: 2025-11-09 01:33:57.949140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b51b0ac06f6'
down_revision: Union[str, Sequence[str], None] = '8042c4d8a60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binary_metric_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('scalar_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('binary_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['binary_metric_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('journal_binary_metric_logs',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('binary_metric_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['binary_metric_id'], ['binary_metrics.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'binary_metric_id')
    )
    op.create_table('journal_scalar_metric_logs',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('scalar_metric_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['scalar_metric_id'], ['scalar_metrics.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'scalar_metric_id')
    )
    op.drop_table('metric_logs')
    op.drop_table('metric_options')
    op.drop_table('metric_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metric_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='metric_categories_pkey'),
    sa.UniqueConstraint('label', name='metric_categories_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('metric_options',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metric_options_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['metric_categories.id'], name='metric_options_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='metric_options_pkey'),
    sa.UniqueConstraint('label', name='metric_options_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('metric_logs',
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('metric_logs_journal_entry_id_fkey')),
    sa.ForeignKeyConstraint(['metric_option_id'], ['metric_options.id'], name=op.f('metric_logs_metric_option_id_fkey')),
    sa.PrimaryKeyConstraint('journal_entry_id', 'metric_option_id', name=op.f('metric_logs_pkey'))
    )
    op.drop_table('journal_scalar_metric_logs')
    op.drop_table('journal_binary_metric_logs')
    op.drop_table('binary_metrics')
    op.drop_table('scalar_metrics')
    op.drop_table('binary_metric_categories')
    # ### end Alembic commands ###
