"""Added in 'content' field for 'user_feedback' - because I forgot to do it previously

Revision ID: 91a1d8717ec7
Revises: 4749908a2864
Create Date: 2025-10-25 01:14:58.875025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a1d8717ec7'
down_revision: Union[str, Sequence[str], None] = '4749908a2864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feedback', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feedback', 'content')
    # ### end Alembic commands ###
