"""Fixed composite primary key for 'saved_edu_articles_

Revision ID: b6dbb64cc835
Revises: e3f64d9b4133
Create Date: 2025-10-27 04:17:38.722637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dbb64cc835'
down_revision: Union[str, Sequence[str], None] = 'e3f64d9b4133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_edu_articles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_edu_articles', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
