"""Fixed schema for scalar metrics

Revision ID: de7b0922b9a6
Revises: 5b51b0ac06f6
Create Date: 2025-11-09 01:51:52.688769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7b0922b9a6'
down_revision: Union[str, Sequence[str], None] = '5b51b0ac06f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_scalar_metric_logs', sa.Column('value', sa.Float(), nullable=False))
    op.drop_column('scalar_metrics', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scalar_metrics', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('journal_scalar_metric_logs', 'value')
    # ### end Alembic commands ###
