"""Removed 'logged_at' from 'metric_logs'. It is really just meant to be a junction table with no extra attributes

Revision ID: e3f64d9b4133
Revises: 91a1d8717ec7
Create Date: 2025-10-25 01:43:37.444963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f64d9b4133'
down_revision: Union[str, Sequence[str], None] = '91a1d8717ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_logs', 'logged_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_logs', sa.Column('logged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
