"""Initial revision

Revision ID: f1533bf98f23
Revises: 
Create Date: 2025-10-24 15:56:00.182666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1533bf98f23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('medical_credential_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('metric_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('edu_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['edu_article_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_img_url', sa.String(), nullable=False),
    sa.Column('credential_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_option_id'], ['medical_credential_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['metric_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('users',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnant_women',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_edu_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saver_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['edu_articles.id'], ),
    sa.ForeignKeyConstraint(['saver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'saver_id', 'article_id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_specialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('medical_credential_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_credential_id'], ['medical_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bump_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('bump_img_url', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['pregnant_women.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('volunteer_specialist_id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'MISSED', name='consultstatus'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['pregnant_women.id'], ),
    sa.ForeignKeyConstraint(['volunteer_specialist_id'], ['volunteer_specialists.id'], ),
    sa.PrimaryKeyConstraint('volunteer_specialist_id', 'mother_id', 'start_time')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['pregnant_women.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_volunteer_specialists',
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_specialist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['pregnant_women.id'], ),
    sa.ForeignKeyConstraint(['volunteer_specialist_id'], ['volunteer_specialists.id'], ),
    sa.PrimaryKeyConstraint('mother_id', 'volunteer_specialist_id')
    )
    op.create_table('thread_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('commenter_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['community_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_logs',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('metric_option_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['metric_option_id'], ['metric_options.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'metric_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_logs')
    op.drop_table('thread_comments')
    op.drop_table('saved_volunteer_specialists')
    op.drop_table('journal_entries')
    op.drop_table('consultations')
    op.drop_table('bump_entries')
    op.drop_table('volunteer_specialists')
    op.drop_table('user_feedback')
    op.drop_table('saved_edu_articles')
    op.drop_table('pregnant_women')
    op.drop_table('community_threads')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('metric_options')
    op.drop_table('medical_credentials')
    op.drop_table('edu_articles')
    op.drop_table('roles')
    op.drop_table('metric_categories')
    op.drop_table('medical_credential_options')
    op.drop_table('edu_article_categories')
    # ### end Alembic commands ###
