"""Added push tokens, some cleanup

Revision ID: fedb5071bb81
Revises: de7b0922b9a6
Create Date: 2025-11-09 03:07:52.608889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedb5071bb81'
down_revision: Union[str, Sequence[str], None] = 'de7b0922b9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expo_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scalar_metrics', sa.Column('unit_of_measurement', sa.String(length=128), nullable=False))
    op.alter_column('scalar_metrics', 'label',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_unique_constraint(None, 'scalar_metrics', ['unit_of_measurement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scalar_metrics', type_='unique')
    op.alter_column('scalar_metrics', 'label',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('scalar_metrics', 'unit_of_measurement')
    op.drop_table('expo_push_tokens')
    # ### end Alembic commands ###
